import sys

if len(sys.argv) < 3:
    sys.exit(1)

out_file = sys.argv[1]
mechanisms = [m.strip() for m in sys.argv[2].split(";") if m.strip()]

with open(out_file, "w") as f:
    f.write("// AUTO-GENERATED BY generate_registry.py\n")
    f.write("#include \"exaero/registry.hpp\"\n")
    f.write("#include \"exaero/dispatcher.hpp\"\n")
    f.write("#include <stdexcept>\n")
    for mech in mechanisms:
        f.write(f"#include \"{mech}.hpp\"\n")

    f.write("\nnamespace exaero {\n")
    f.write("bool Registry::has_mechanism(const std::string& name) {\n")
    for mech in mechanisms:
        f.write(f"    if (name == \"{mech}\") return true;\n")
    f.write("    return false;\n")
    f.write("}\n\n")

    f.write("void Registry::dispatch(ExaeroContext& ctx, UnmanagedDeviceState& state, double dt) {\n")
    for mech in mechanisms:
        f.write(f"    if (ctx.active_mechanism == \"{mech}\") {{\n")
        f.write(f"        Dispatcher::dispatch<mkpp::SolverKernels<Kokkos::DefaultExecutionSpace>>(ctx, state, dt);\n")
        f.write(f"        return;\n")
        f.write(f"    }}\n")

    f.write("    throw std::runtime_error(\"Mechanism not found in Registry: \" + ctx.active_mechanism);\n")
    f.write("}\n")
    f.write("} // namespace exaero\n")
